//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.15
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub b362507e-acb9-4c4c-9758-a6e2a87b2874 aws-my-sample-app-android-v0.15";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("us-east-1");
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:32b6e9cc-44a6-4e9b-8139-51f4db98902c";
    public static final String AMAZON_COGNITO_USER_POOL_ID =
        "us-east-1_fStupRAy1";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
        "2pg8drkiav1rnld2p45pb5gksa";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
        "1e1u04dvbp8o9nftj0gnm665casqr7l0jejabgg9vpvc53sjsua0";
}
